language: java
script: mvn package
deploy:
  provider: script
  script: "./travis/deploy.sh"
  on:
    branch: master
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - GPG_KEY_NAME=navikt
  - secure: QqrQbX5mrmaSSK9QbPAw3hwQWBXTtH4A6a7IO3M/FZs2nUmEXvSFQChGA0GUxE00r2As4p3t5VbRt8mp5jf3bR0xNpnWq9zaorufF2BXWRflPxaLDQ7+chVwTXSTScmYL4hI9emHX9f3p2/De3r3EJ4rpHgznC6aSi/PQ5Ux5DnJ5uuS1geegD6Fs8FbR7LQcko5h+0b4JJrF5uoHD/8eiRdEBQ/y0X6PEFqcVuLAhQA0pLPt2X3CR2gz5SrIULzDz+3zas5BZDZbh8h8ILGZINlxcnQXTP26wJkaNEoXQdq13Grhxl1h9rlVX2izq8t3+Icmk9/jYk6/LeNtcMfgCS60EUIpXnp3FdSt4LVePbMCv0yxrpu0z71p93Yy/R3W/xGixNfa1vXOvPNUtvRRlMRgKEiowU4SqXlYiFqfgb90SeuOOAsSqv1E+lPY6pSs28QWc69s9T4wE/BPgOCLVjCaFlaCrfU0E44fdhw/zCl85I7ybgjnj37ll1meRZilYwTCIiAzKi6iQC5SfdJda65ur127SsLkvYR+6snmSkGl2qqawCN+KjKhGp2iYKUb9VXDAPAzlTkzQkv1WS4DfU9jpZhgS05rlrIe7wYRGaomwbt/CzjPPonf85X2psJXaf7zfzCCm3Rh0LWg5FERZq6yRiymkVy299dh/UOnpg=
  - secure: iaTbwwv4rvWYE3KwN0K/PX2HWGdrJZX+o3UraEN9lCbGnDVyBYRa7h1aaQf2QXHdpJIfQcEQOqXtZ+540nS1P+hes0dDwerb2iuQYaQgJJhyZGP3490ZNfajTdHlUsuSATHAvrVMe4cIMiRPnAGrMXtXdqr+J95E/rI9n14FqT3EkSEqHf/oZmLc3BpuJkVMoX1wBeDTm3qs7gdXoOv2LmCVLc9QWT69/vsxdhzPEuP+UFxxqGrBAiyiTI6mZrClI0ZMTEAjrMriD0gJk44dqwCh6Wio7YPWpP7S+g2UrbWQszVLNDd0IXdE4jSqMDMLTJ5ZV5vBozK9y9q7a9Ni57OOvBo9lINJ3sv+beXUyZD3jNuXc0WukvIO49YviKDO7LBTOpxqUvPPyR4D3HPa0+wCG6D2itmpnvuboWQtB/wgzAicCJaXXZ63UGSbLp83Yt8e64RnNqRw8B05DGmj/qRypK5ch5eWDsbrtP5eR29qzOxb/AlDqNWahU6m3zLwu6LJU7LUJ3jFMZU6Yck7pLjMJsbi43UVMuFH/3xvbbgc7fapQtHuhUwf9XW81HqNvTBxXeDQMA1nvfkzmVVAQi02zrCmixaaWyLUmhg+Ja0qkMX950P1spZNVmhv6MPzFR6QcjBVio1X7zBr4SZt0fWVIY9FRQTfN9rQ/mZUy9w=
