language: java
script: mvn package
deploy:
  skip_cleanup: true
  provider: script
  script: "./travis/deploy.sh"
  on:
    branch: master
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - GPG_KEY_NAME=navikt
  - secure: FekSj5zSgDnp2UJePmurwDukItWMCrE1R8JGiL8uLCtZwK7Diz0FHlz29fiNigzcLA1pfRaZF49nJFmZsQRwAzNR94I79MGjGhpijU2m/rtzQ6Zscm73RRnia3KT5dQO4P723C2ztVyO0QZMKU1KPpMDkqfBGJEzTlCLza0FusDjAPxMnSqSXw97RzR/WtO+BBEvgbTvBcmhkqVkgpU3uisSrGeoXOCzwwYKzq2WLtUgM3Hliu0yOft2LwcLMR/YtO7l7y5AD+xoW5QniQFAwwHfOTuJhVaaM5k6DMmtFiHl3qEscXPuTuEMlT/HrEONHeL1OFTuAHDdNDbmFQFyiwPnjZ9sM5JKCJelrahzX7ctzF8lzy/AIX2MkDOWiC+06hitdVgyBB+6dN0KA/XmkxyG6oiePPCmC8OXYBsuCFFAgOBu3gZ6w9NYdku2/WVRIiiJlbIFVyX9z9ht0p0HE02PoA1ojCe0yFJp4xfTYmXJNp04xmfsw6cYGI8qbrmrZf74RR55QVJX+5yMWKm7/WJ6dZYiiMkPhrlQFSYwZ1J0dPh4QA1uE0Rh4a/eUXVAuCY6XBBiZtTQwFeM5XO5uaLeS2xG5ZfQUWDB8PnQrRBFK/xSaZ+hStWfojR3gPoKE3GeEXLINoZMMXjkyzspBC9jF754k9UyIlabTuEnruk=
  - secure: ludGWniVsRUbfvidk+OpcY5tOzE1nc3NhueXfVDU/3+Eh0qbXPyOdJh5oTpOX/F8fxYYSVOIuhgMJcVg0SclB/iqJlumISWSIbyaVcETb1nmasAwe9f+B4iZWU0y7l0yJWSuwUcLjxGG4IL6lI9FkkhEwOpX1U7zMDQI16uRDOY2UhJ0Yg5rmX7A4gqNEnaI0cMTKd582S27pBYOy2a9SVcXJAO+fBsOnvt98R4TScsYJooqK27lADisertDNFy2CoaVHHFRepApNXijVTCVET8zN69JAdPMcseObsYcr2WVT7FWyt1VH4b3iV9DatfIOotMI+lqMMiRnQ2VcDdJfcQk1Ny0hramYQT1vrlt0iJ9jEiiXuUnrtuFjRhw3pONpYysz2IoIdlyUCJN96Nvy/cvTRVfSVS2Qv8/G7kdF9LZC5qeNaq/Ng0tEL3JyLZdF/H5WoijF9WS052Hkb8IompbhjGz1dHqwwpCqqYZoibPuel7TVNBxJTF9JXP0r4DwgqSB3sHNm9S2MPoq1a07Cpz0UHnV0q9ggFFf5ZtzG2gocx7inswBRZyRAWD5rnLiozqYn2zQao1z7sWs+PQDE/AANopIQkLY6FyPLF0WFlopbjxG8XFXiBg0L/tT3JfcquctZuai17UEwePOjck6LncjfdhcvPxxda+yF8hwgM=
